//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBankConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WebBank")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanRequest", Namespace="http://schemas.datacontract.org/2004/07/WebBank")]
    [System.SerializableAttribute()]
    public partial class LoanRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CreditScorek__BackingFieldField;
        
        private double LoanAmmountk__BackingFieldField;
        
        private string LoanDurationk__BackingFieldField;
        
        private string ssnk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreditScore>k__BackingField", IsRequired=true)]
        public int CreditScorek__BackingField {
            get {
                return this.CreditScorek__BackingFieldField;
            }
            set {
                if ((this.CreditScorek__BackingFieldField.Equals(value) != true)) {
                    this.CreditScorek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreditScorek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LoanAmmount>k__BackingField", IsRequired=true)]
        public double LoanAmmountk__BackingField {
            get {
                return this.LoanAmmountk__BackingFieldField;
            }
            set {
                if ((this.LoanAmmountk__BackingFieldField.Equals(value) != true)) {
                    this.LoanAmmountk__BackingFieldField = value;
                    this.RaisePropertyChanged("LoanAmmountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LoanDuration>k__BackingField", IsRequired=true)]
        public string LoanDurationk__BackingField {
            get {
                return this.LoanDurationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanDurationk__BackingFieldField, value) != true)) {
                    this.LoanDurationk__BackingFieldField = value;
                    this.RaisePropertyChanged("LoanDurationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ssn>k__BackingField", IsRequired=true)]
        public string ssnk__BackingField {
            get {
                return this.ssnk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ssnk__BackingFieldField, value) != true)) {
                    this.ssnk__BackingFieldField = value;
                    this.RaisePropertyChanged("ssnk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversalResponse", Namespace="http://schemas.datacontract.org/2004/07/WebBank")]
    [System.SerializableAttribute()]
    public partial class UniversalResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal interestratek__BackingFieldField;
        
        private string ssnk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<interestrate>k__BackingField", IsRequired=true)]
        public decimal interestratek__BackingField {
            get {
                return this.interestratek__BackingFieldField;
            }
            set {
                if ((this.interestratek__BackingFieldField.Equals(value) != true)) {
                    this.interestratek__BackingFieldField = value;
                    this.RaisePropertyChanged("interestratek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ssn>k__BackingField", IsRequired=true)]
        public string ssnk__BackingField {
            get {
                return this.ssnk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ssnk__BackingFieldField, value) != true)) {
                    this.ssnk__BackingFieldField = value;
                    this.RaisePropertyChanged("ssnk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebBankConsole.ServiceReference1.CompositeType GetDataUsingDataContract(WebBankConsole.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebBankConsole.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebBankConsole.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HandleRequest", ReplyAction="http://tempuri.org/IService1/HandleRequestResponse")]
        WebBankConsole.ServiceReference1.UniversalResponse HandleRequest(WebBankConsole.ServiceReference1.LoanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HandleRequest", ReplyAction="http://tempuri.org/IService1/HandleRequestResponse")]
        System.Threading.Tasks.Task<WebBankConsole.ServiceReference1.UniversalResponse> HandleRequestAsync(WebBankConsole.ServiceReference1.LoanRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebBankConsole.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebBankConsole.ServiceReference1.IService1>, WebBankConsole.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebBankConsole.ServiceReference1.CompositeType GetDataUsingDataContract(WebBankConsole.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebBankConsole.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebBankConsole.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WebBankConsole.ServiceReference1.UniversalResponse HandleRequest(WebBankConsole.ServiceReference1.LoanRequest request) {
            return base.Channel.HandleRequest(request);
        }
        
        public System.Threading.Tasks.Task<WebBankConsole.ServiceReference1.UniversalResponse> HandleRequestAsync(WebBankConsole.ServiceReference1.LoanRequest request) {
            return base.Channel.HandleRequestAsync(request);
        }
    }
}
